- name: core Ubuntu configuration
  become: yes
  hosts: "tag_Project_chronam:&tag_DeploymentCluster_{{ deployment_cluster }}"
  vars_files:
      - vault.yml
  handlers:
      - import_tasks: handlers.yml
  tasks:
      - name: ensure telnet is not installed (CIS 2.3.4)
        package: name=telnet state=absent

      - name: Install CIS modprobe rules for risky kernel modules
        copy:
            dest: /etc/modprobe.d/CIS.conf
            src: files/CIS/modprobe.d/CIS.conf
            mode: 0755

      - name: Install auditing tools
        package:
            name: "{{ packages }}"
            state: present
        vars:
            packages:
                - auditd
                - aide

      - name: Check for Postfix
        package:
            name: postfix
            state: present
        check_mode: true
        register: pkg_postfix

      - name: Configure Postfix only to listen on localhost
        shell: postconf -e "inet_interfaces = localhost"
        when: not pkg_postfix.changed
        notify: restart postfix

      - name: "Don't have AIDE scan itself"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_aide
            line: "!/var/lib/aide"

      - name: "Don't have AIDE scan /run"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_run
            line: "!/run"

      - name: "Don't have AIDE scan /srv"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_srv
            line: "!/srv"

      - name: "Don't have AIDE scan /mnt"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_mnt
            line: "!/mnt"

      - name: "Don't have AIDE scan /var/lib/lxcfs"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_lib_lxcfs
            line: "!/var/lib/lxcfs"

      - name: "Don't have AIDE scan Postfix"
        blockinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_postfix
            block: |
                !/var/spool/postfix
                !/var/lib/postfix

      - name: "Don't have AIDE scan systemd"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_systemd
            line: "!/var/lib/systemd"

      - name: "Don't have AIDE scan package management"
        blockinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_apt
            block: |
                !/var/backups
                !/var/lib/apt
                !/var/lib/dpkg
                !/var/lib/snap
                !/var/lib/ubuntu-release-upgrader
                !/var/lib/ucf
                !/var/lib/update-notifier

      - name: "Don't have AIDE scan /var/cache"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_cache
            line: "!/var/cache"

      - name: "Don't have AIDE scan DHCP leases"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_dhcp
            line: "!/var/lib/dhcp"

      - name: "Don't have AIDE scan /var/lib/varnish"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_lib_varnish
            line: "!/var/lib/varnish"

      - name: "Don't have AIDE scan /opt/solr"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_solr
            line: "!/opt/solr"

      - name: "Don't have AIDE scan /var/log"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_log
            line: "!/var/log"

      - name: "Don't have AIDE scan /var/tmp"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_tmp
            line: "!/var/tmp"

      - name: "Don't have AIDE scan /var/spool"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_var_spool
            line: "!/var/spool"

      - name: "Don't have AIDE scan cloud-init files"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_cloud_init
            line: "!/var/lib/cloud"

      - name: "Don't have AIDE scan /var/lib/amazon/ssm"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_amazon_ssm_agent_state
            line: "!/var/lib/amazon/ssm"

      - name: "Don't have AIDE scan Qualys"
        lineinfile:
            create: yes
            mode: u=rw,g=r,o=r
            path: /etc/aide/aide.conf.d/99_skip_qualys
            line: "!/usr/local/qualys"

      - name: "Restrict su to the wheel group (CIS 5.6)"
        lineinfile:
            path: /etc/pam.d/su
            line: "auth required pam_wheel.so use_uid"
            regexp: ".* pam_wheel.so .*"
        when: ansible_distribution=="Ubuntu"

      - name: disable core dumps (CIS 1.5.1)
        sysctl:
            name: fs.suid_dumpable
            value: "0"
            reload: yes

      - name: disable source routing (CIS 3.2.1)
        sysctl:
            name: "{{ item }}"
            value: "0"
            sysctl_set: yes
            reload: yes
        with_items:
            - net.ipv4.conf.all.accept_source_route
            - net.ipv4.conf.default.accept_source_route

      - name: disable ICMP redirects (CIS 3.2.2)
        sysctl:
            name: "{{ item }}"
            value: "0"
            sysctl_set: yes
            reload: yes
        with_items:
            - net.ipv4.conf.all.accept_redirects
            - net.ipv4.conf.default.accept_redirects

      - name: disable “secure” ICMP redirects (CIS 3.2.3)
        sysctl:
            name: "{{ item }}"
            value: "0"
            sysctl_set: yes
            reload: yes
        with_items:
            - net.ipv4.conf.all.secure_redirects
            - net.ipv4.conf.default.secure_redirects

      - name: log martians (CIS 3.2.4)
        sysctl:
            name: "{{ item }}"
            value: "1"
            sysctl_set: yes
            reload: yes
        with_items:
            - net.ipv4.conf.all.log_martians
            - net.ipv4.conf.default.log_martians

      - name: "SSH: restrict access to required users (CIS 5.2.14)"
        lineinfile:
            path: /etc/ssh/sshd_config
            line: "AllowUsers ubuntu ndnp"
            regexp: "^AllowUsers"
        when: ansible_distribution=="Ubuntu"
        notify: restart ssh

      - name: "SSH: set max auth tries (CIS 5.2.5)"
        lineinfile:
            path: /etc/ssh/sshd_config
            line: "MaxAuthTries 4"
            regexp: "^MaxAuthTries"
        notify: restart ssh

      - name: "SSH: disable X11 forwarding (CIS 5.2.4)"
        lineinfile:
            path: /etc/ssh/sshd_config
            line: "X11Forwarding no"
            regexp: "^X11Forwarding"
        notify: restart ssh

      - name: "SSH: set login grace time (CIS 5.2.13)"
        lineinfile:
            path: /etc/ssh/sshd_config
            line: "X11Forwarding no"
            regexp: "^X11Forwarding"
        notify: restart ssh

      - name: "SSH: completely block root logins"
        lineinfile:
            path: /etc/ssh/sshd_config
            # Ubuntu defaults to PermitRootLogin prohibit-password but we'll go a step further:
            line: "PermitRootLogin no"
            regexp: "^PermitRootLogin"
        notify: restart ssh

      - name: "SSH: disable PermitUserEnvironment (CIS 5.2.10)"
        lineinfile:
            path: /etc/ssh/sshd_config
            line: "PermitUserEnvironment no"
            regexp: "^PermitUserEnvironment"
        notify: restart ssh

      - name: "SSH: restrict access to sshd config (CIS 5.2.1)"
        file:
            path: /etc/ssh/sshd_config
            mode: 0600
            owner: root
            group: root
        notify: restart ssh

      - name: "cron: restrict /etc/crontab (CIS 5.1.2)"
        file:
            path: /etc/crontab
            mode: 0600
            owner: root
            group: root

      - name: "cron: restrict /etc/cron.hourly (CIS 5.1.3)"
        file:
            path: /etc/cron.hourly
            mode: 0700
            owner: root
            group: root

      - name: "cron: restrict /etc/cron.daily (CIS 5.1.4)"
        file:
            path: /etc/cron.daily
            mode: 0700
            owner: root
            group: root

      - name: "cron: restrict /etc/cron.weekly (CIS 5.1.5)"
        file:
            path: /etc/cron.weekly
            mode: 0700
            owner: root
            group: root

      - name: "cron: restrict /etc/cron.monthly (CIS 5.1.6)"
        file:
            path: /etc/cron.monthly
            mode: 0700
            owner: root
            group: root

      - name: "cron: restrict /etc/cron.d (CIS 5.1.7)"
        file:
            path: /etc/cron.d
            mode: 0700
            owner: root
            group: root
