- name: Configure a user for LC ITSG compliance scans
  become: yes
  hosts: "tag_Project_chronam:&tag_DeploymentCluster_{{ deployment_cluster }}"
  vars_files:
      - vault.yml
  handlers:
      - import_tasks: handlers.yml
  tasks:
      - name: Creating user account for Qualys
        user:
            name: itsg-scans
            groups:
                - sudo

      - name: create ~/itsg-scans/.ssh directory
        file:
            path: /home/itsg-scans/.ssh
            state: directory
            mode: 0700
            owner: itsg-scans
            group: itsg-scans

      - name: "install itsg-scans user's authorized_keys file"
        copy:
            dest: /home/itsg-scans/.ssh/authorized_keys
            src: files/itsg-scans-authorized_keys
            mode: 0700
            owner: itsg-scans
            group: itsg-scans
