{
 "title": "ChronAm Production",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "ChronAm Prod Load Balancer",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "alias": "5xx",
     "dimensions": {
      "LoadBalancer": "app/chronam-prod-public/ba40f177bbebf225"
     },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "2xx",
     "dimensions": {
      "LoadBalancer": "app/chronam-prod-public/ba40f177bbebf225"
     },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "3xx",
     "dimensions": {
      "LoadBalancer": "app/chronam-prod-public/ba40f177bbebf225"
     },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "4xx",
     "dimensions": {
      "LoadBalancer": "app/chronam-prod-public/ba40f177bbebf225"
     },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Varnish Backend Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(varnish_backend_req{Environment=\"Production\"}[5m]))",
     "legendFormat": "Request/s"
    },
    {
     "expr": "sum(rate(varnish_main_backend_fail{Environment=\"Production\"}[5m]))",
     "legendFormat": "Failure/s"
    },
    {
     "expr": "sum(rate(varnish_main_backend_busy{Environment=\"Production\"}[5m]))",
     "legendFormat": "Busy/s"
    }
   ]
  },
  {
   "title": "Varnish Client Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(varnish_main_client_req{Environment=\"Production\"}[5m]))",
     "legendFormat": "Request/s"
    },
    {
     "expr": "sum(rate(varnish_main_client_req_400{Environment=\"Production\"}[5m]))",
     "legendFormat": "400/s"
    }
   ]
  },
  {
   "title": "Apache Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{Environment=\"Production\",state!=\"idle\"}",
     "legendFormat": "{{ instance_id }}: {{ state }}"
    }
   ]
  },
  {
   "title": "App Server Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpout{Environment=\"Production\", Name=\"Chronam Web App\"}[5m])",
     "legendFormat": "Swap-Outs: {{ instance_id }}"
    },
    {
     "expr": "node_load1{Environment=\"Production\", Name=\"Chronam Web App\"}",
     "legendFormat": "Load: {{ instance_id }}"
    }
   ]
  },
  {
   "title": "Predicted Free Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_free_bytes[1h], 86400) < 0",
     "legendFormat": "{{ instance_id }} ({{ Environment }} — {{ Name }} — {{ DeploymentCluster }}): {{ mountpoint }}",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Local Storage Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{fstype!=\"squashfs\",fstype!=\"tmpfs\"} / node_filesystem_size_bytes)",
     "legendFormat": "{{ instance_id }} ({{ Environment }} — {{ Name }} - {{ DeploymentCluster }}): {{ mountpoint }}",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}