#!/bin/sh

set -eu

if ! /opt/chronam/ENV/bin/python --version >/dev/null 2>/dev/null; then
    echo "Python install is broken!"
    exit 2
fi

if ! systemctl is-enabled --quiet apache2.service; then
    exit 0
fi

if ! curl --output /dev/null --silent --show-error --max-time 10 --retry 6 --retry-delay 10 --retry-connrefused --fail http://localhost:80/healthz; then
    echo "Apache failed the healthcheck"

    if [ "$(cut -f1 -d. /proc/uptime)" -gt 900 ]; then
        sudo reboot
        exit 1
    else
        echo "System appears to have recently booted; waiting for it to stabilize"
        exit 0
    fi
fi
